### ISSUE TITLE
Add windows and mac build on travis

### ISSUE THREAD

**Issue by mavogel** [terraform-providers/terraform-provider-docker#100]
Travis supports now builds on windows: https://blog.travis-ci.com/2018-10-11-windows-early-release 🎉 

- Add this to build matrix
- Remove `appveyor` configuration

//cc @AndreLouisCaron

**Comment by AndreLouisCaron** [comment]
Sweet!

**Comment by mavogel** [comment]
add mac as well: https://docs.travis-ci.com/user/reference/osx/
