### ISSUE TITLE
docs/docker_container: "network advanced" documentation is incorrect

### ISSUE THREAD

**Issue by rboyer** [terraform-providers/terraform-provider-docker#109]
It reads:

> Network advanced
> 
> networks_advanced is a block within the configuration that can be repeated to specify files to upload to the container before starting it. Each networks_advanced supports the following:

But that's a cut-and-paste from the prior section and is incorrect as is.

> File Upload
> 
> upload is a block within the configuration that can be repeated to specify files to upload to the container before starting it. Each upload supports the following

**Comment by mavogel** [comment]
Yes, good catch! Documentation will be updated with `v1.1.1` and I'll double check for copy paster in the future
