### ISSUE TITLE
docker_service resource truncates env variable in state if it has "=" in it

### ISSUE THREAD

**Issue by akomlik** [terraform-providers/terraform-provider-docker#121]
### Terraform Version
`Terraform v0.11.11`
`+ provider.docker v1.1.0`

### Affected Resource(s)
- docker_service

### Terraform Configuration Files
```hcl
resource "docker_service" "foo" {
  name     = "foo-service"
  task_spec {
    container_spec {
      image = "nginx:latest"
      env {
        URI = "/api-call?param1=value1"
      }
    }
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://gist.github.com/akomlik/cb664fd083241fc36acc9c687fe3d5ed

### Expected Behavior
Resource created and following "plan" should show no changes

### Actual Behavior
- Service is correctly created with environment var including "=" in it:
`$ docker service inspect foo-service --format "{{json .Spec.TaskTemplate.ContainerSpec.Env}}"`
`["URI=/api-call?param1=value1"]`

- however Terraform state has it truncated:
`$ terraform state pull | grep container_spec.0.env.URI`
`                            "task_spec.0.container_spec.0.env.URI": "/api-call?param1",`

- as a result all consecutive runs of "plan" show that env variable needs a "fix":
`$ terraform plan`
`Terraform will perform the following actions:`
`  ~ docker_service.foo`
`      task_spec.0.container_spec.0.env.URI: "/api-call?param1" => "/api-call?param1=value1"`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

**Comment by hatched-DavidMichon** [comment]
Is there a workaround for this until it's fixed in the provider? I see this issue being pushed from milestones to milestones

**Comment by mavogel** [comment]
Yes, that's true. There was a delay in reviewing. This issue will be tackled in the next milestone. Feel free to contribute as well
