### ISSUE TITLE
Upgrade to TF 0.12

### ISSUE THREAD

**Issue by mavogel** [terraform-providers/terraform-provider-docker#144]
Update the provider to TF 0.12

- https://www.terraform.io/upgrade-guides/0-12.html
- go get github.com/hashicorp/terraform@v0.12.0-beta2
- TBD

**Comment by manfredlift** [comment]
When might this be released?

**Comment by mavogel** [comment]
I'll trigger it this week

**Comment by hatched-DavidMichon** [comment]
@mavogel will it still be planned to be released this week?

**Comment by manfredlift** [comment]
@mavogel, any chance of releasing this soon? 🙏

**Comment by giacomocariello** [comment]
@mavogel I'm chiming in to request a release.

**Comment by mavogel** [comment]
sorry for the delay in answering due to holidays: release is out for a couple of days now: https://releases.hashicorp.com/terraform-provider-docker/2.0.0/

**Comment by hatched-DavidMichon** [comment]
@mavogel thx!
