### ISSUE TITLE
Docker nat network still present on Windows OS

### ISSUE THREAD

**Issue by dExecutioner** [terraform-providers/terraform-provider-docker#145]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

Affected Resource(s)
* docker networks 

## Please refer to the issue:
https://github.com/hashicorp/terraform/issues/12095 

fixed by #587988c, which also needs fixing for Windows where the default network is called "nat". 

## Expected Behavior
With only one network in the list, I would expect only one 'eth0' interface inside the running container
## Actual Behavior
I get the default bridge and the network from the list.

## Terraform Version
Terraform v0.11.2

**Comment by mavogel** [comment]
@dExecutioner could you please provide an example configuration?

**Comment by dExecutioner** [comment]
> @dExecutioner could you please provide an example configuration and output? Unfortunately, I do not have access to a Windows machine atm

Hello - Here is the example configuration and screen shots:

resource "docker_container" "MyApp" {
   name     = "App"
  image    = "myapp:1.0"
  hostname = "EU11111ABC01"
  restart = "on-failure"
  max_retry_count="5"
  dns = ["${var.DNS}"]       
  networks_advanced  {
    name = "${var.DockerVLanGreen}"
    ipv4_address = "${var.AppContainerIP}"
	aliases = ["EU11111WST01"]
  }

env = ["START_NP6=${var.NP6Startup}",
  "DOCKER_HOST_NAME=${var.StoreName}CMS${var.MachineNumber}",
  "CONNECTION_ID=${var.Connection_ID}",
  "SMARTUPDATE_SERVER_URL=http://${var.StoreName}SUD${var.MachineNumber}",
  "NPSHARP_ARGUMENTS=-DPluginIsolationStrategy=ByName -DSystemMonitor.PluginMemoryCriticalThreshold=900 -DNp6Integrator.MaxNumberOfPOSPerPosDb=1 ${(var.MachineNumber == "01") ? "" : var.FailoverForNode }"]
  volumes {
    host_path="s:\\Docker\\app"
    container_path="c:\\app"
  }
}

Please check the screen shot 'Custom terraform x5.PNG' from custom compiled terraform provider   which I have compiled. Also, check the screenshot 'Terraform x4.PNG' from the terraform provider compiled by hashicorp. 

Also, I am attaching the code change I have done to fix it, Please look at the screen shot 'Codechange.PNG' I have changed bridge mode to nat. 
![Codechange](https://user-images.githubusercontent.com/42977310/74550269-fed78c00-4f48-11ea-8bf7-071eeb3407af.PNG)
