### ISSUE TITLE
Support for "--workdir"

### ISSUE THREAD

**Issue by andresvia** [terraform-providers/terraform-provider-docker#146]
### Terraform Version

`0.11.14`

### Affected Resource(s)

`docker_container`

### Terraform Configuration Files

```
resource "docker_container" "foo" {
  //...
  workdir = "/bar"
  //...
}
```

### Expected Behavior

The workdir parameter should be supported.

### Actual Behavior
The workdir parameter is not supported.

### References

`-w, --workdir string                 Working directory inside the container`

**Comment by cyrilgdn** [comment]
There's an opened PR #118 for that. I'll probably do the modifications I asked in the PR as it's just little stuff and the author does not seem to have the time for the moment.
