### ISSUE TITLE
release 1.2

### ISSUE THREAD

**Issue by pjvds** [terraform-providers/terraform-provider-docker#155]
There is some serious unreleased goodness including ssh protocol support, fix for local image pulling and container mounts support.

Is there any reason this is not released yet?

**Comment by mavogel** [comment]
Hi @pjvds, yes there is a reason. The tests run locally and fine on travis but not in HashiCorps' CI, which is responsible for releasing the provider. Currently, I'm on it to debug an fix the issue. I'll keep you updated and we try to release ASAP. Sorry for the delay

**Comment by pjvds** [comment]
@mavogel it would be great to see this fly soon, let me know if I can provide any help!

**Comment by mavogel** [comment]
#154 will do it. Waiting for a review

**Comment by mavogel** [comment]
`v1.2.0` is released. #154 will go into the next release to fix the flaky tests.

**Comment by pjvds** [comment]
Great news @mavogel 👍

**Comment by sandys** [comment]
hi guys. sorry to comment on a closed issue, but i wasnt sure whether to open a new one. 

the main documentation still doesnt have the ssh part included. is this still unreleased ? https://www.terraform.io/docs/providers/docker/index.html

**Comment by mavogel** [comment]
Good catch. Will update the docs on the next release

**Comment by Teutone** [comment]
Regarding docs about `mounts` - I noticed a divergence:

In the [code](https://github.com/terraform-providers/terraform-provider-docker/blob/master/docker/resource_docker_container.go):
`mounts`
- volume_options
  - no_copy
  - labels
  - driver_name
  - driver_options

In the [docs website](https://www.terraform.io/docs/providers/docker/r/container.html#mounts-1):
- volume_options
  - no_copy
  - labels
  - driver_**config**
  - **name**
  - **options**
  

Thanks for this great provider!
