### ISSUE TITLE
Removing the 'ports' block doesn't do anything to the container

### ISSUE THREAD

**Issue by mavidser** [terraform-providers/terraform-provider-docker#167]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v0.11.7
+ provider.docker v2.1.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- docker_container

### Terraform Configuration Files
```hcl
resource "docker_container" "myapp" {
  image = "myapp:latest"
  name  = "myapp"
  restart = "unless-stopped"
  destroy_grace_seconds = 30
  must_run = true
  ports {
    internal = 9090
    external = 9090
  }
}
```

to

```hcl
resource "docker_container" "myapp" {
  image = "myapp:latest"
  name  = "myapp"
  restart = "unless-stopped"
  destroy_grace_seconds = 30
  must_run = true
}
```

### Expected Behavior
What should have happened?
Terraform should have detected that the ports block has been removed and force a new container with no exposed ports, something like:
```
ports.#:                                   "1" => "0" (forces new resource)
ports.0.external:                          "9080" => "" (forces new resource)
ports.0.internal:                          "9090" => "" (forces new resource)
ports.0.ip:                                "0.0.0.0" => "0.0.0.0"
ports.0.protocol:                          "tcp" => "tcp"
```

### Actual Behavior
What actually happened?
Terraform doesn't reflect anything.
```
No changes. Infrastructure is up-to-date.
```
Even if you update any other variable, the ports section doesn't even appear in the `plan` output.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a docker container with some exposed ports. (codeblock 1 above)
2. `terraform apply`
3. Remove the ports section from the container definition. (codeblock 2 above)
4. `terraform plan`

**Comment by mavogel** [comment]
Thanks @mavidser for pointing this out. Will review your PR
