### ISSUE TITLE
Help wanted: Docker API version 1.25

### ISSUE THREAD

**Issue by dom54** [terraform-providers/terraform-provider-docker#169]
Hi,

We have a requirement to support Docker API 1.25, just after some feedback as to what would be involved.  Is it a case of "latest version should work but some api calls will fail" or is it a complete overhaul of the protocol between the 1.25 and 1.39?

**Comment by dom54** [comment]
Would omitting "withVersion" from the Docker go client be enough? Im going to try it out but I have to learn Go first!

"WithVersion overrides the client version with the specified one. If an empty version is specified, the value will be ignored to allow version negotiation."

**Comment by mavogel** [comment]
Hi @dom54, thank you for the request. We'd need to investigate how easily we could add this. I keep you updated the next days. Feel free to contribute. According to the docker version [matrix](https://docs.docker.com/develop/sdk/#api-version-matrix) you need Docker version `v1.13`

**Comment by dom54** [comment]
So, my first attempt with Go...I checked out the project and did a go install (windows), then copied to my terraform plugin directory. It found the plugin but even without changing a single line of source I get

Error: Error initializing Docker client: protocol not available

  on <empty> line 0:
  (source code not available)

Feel like im missing something obvious..

**Comment by mavogel** [comment]
Hey, I need to revise #100 to verify windows builds and tests. Do you have a linux vm you could develop on?

**Comment by mavogel** [comment]
> Would omitting "withVersion" from the Docker go client be enough? Im going to try it out but I have to learn Go first!

Probably #177 will address this.

**Comment by dom54** [comment]
Great, thanks. I did manage to get it working by changing the client version string in the end

**Comment by mavogel** [comment]
Could you retest with the latest version of the provider?

**Comment by GBSal** [comment]
> Great, thanks. I did manage to get it working by changing the client version string in the end

Can you please provide bit more info how did you fix this issue ? I'm having the same

**Comment by mavogel** [comment]
ping @dom54
