### ISSUE TITLE
destroy_grace_seconds is not adhered to

### ISSUE THREAD

**Issue by laurieodgers** [terraform-providers/terraform-provider-docker#174]
### Terraform Version
0.11 but looking at the code this is still a bug in 0.12 and version 2 of terraform-provider-docker

### Affected Resource(s)
Please list the resources as a list, for example:
- docker_container

### Terraform Configuration Files
```hcl
resource "docker_container" "default" {
  provider = "docker.test"
  name = "docker-container"
  destroy_grace_seconds = "300"
  memory = "256"

  image = "${docker_image.default.name}"
  restart = "always"
  start = true
  must_run = true
  network_mode = "host"

  healthcheck {
    test = [
      "CMD",
      "/healthcheck.sh",
      "eth0",
      "123"
    ]
    interval = "10s"
    timeout = "3s"
    start_period = "3s"
    retries = 1
  }

  log_opts {
    max-size = "50m"
    max-file = "5"
  }

  volumes {
    host_path = "/redacted/host/path/"
    container_path = "/redacted/container/path/"
    read_only = true
  }
}
```

### Debug Output
https://gist.github.com/laurieodgers/e99b6e008fc3ee1b5e71d2a6d3ce9f01

### Expected Behavior
terraform-provider-docker should wait the full 300 seconds for the container to stop gracefully.

### Actual Behavior
terraform-provider-docker does not wait the full destroy_grace_seconds and kills the container before the destroy_grace_seconds period is over.

### Steps to Reproduce
1. Set destroy_grace_seconds to a large number
2. Set up a container that does not stop gracefully, or something that runs for a long period of time
3. `terraform plan`
4. `terraform apply`

### Important Factoids
Using `docker stop -t 300 (container id)` via CLI will cause docker to wait the full 300 seconds before killing the container.

Looking at the code, it looks like terraform-provider-docker waits a random period of time between 0 and destroy_grace_seconds instead of the full period.

See References for a link to the code which invokes rand.Int31n() to generate a timeout period.

### References
- https://github.com/terraform-providers/terraform-provider-docker/blob/master/docker/resource_docker_container_funcs.go#L569

**Comment by laurieodgers** [comment]
I should have a PR for this ready in the next 24 hours - just running through some tests at the moment.

**Comment by mavogel** [comment]
That's it . For new feature it would be to add docs as well, but as this is a bugfix, tests will be fine. thank you!
