### ISSUE TITLE
Error initializing Docker client: protocol not available

### ISSUE THREAD

**Issue by cowwoc** [terraform-providers/terraform-provider-docker#180]
### Terraform Version
Terraform v0.12.7
+ provider.aws v2.25.0
+ provider.docker v2.2.0
+ Microsoft Windows [Version 10.0.18362.295]

### Terraform Configuration Files
```hcl
terraform {
  required_version = "0.12.7"
}

variable "region" {
  default = "us-west-1"
}

provider "aws" {
  version = "~> 2.25"
  profile = "hq"
  region = var.region
}

resource "aws_instance" "sparrow" {
  ami = "ami-0fcdcdb074d2bac5f"
  instance_type = "t2.micro"

  provisioner "local-exec" {
    command = "echo ${aws_instance.sparrow.public_ip} > ip_address.txt"
  }
}

provider "docker" {
  version = "~> 2.2"

  registry_auth {
    address = "registry.hub.docker.com"
    config_file = "${pathexpand("~/.docker/config.json")}"
  }
}

resource "docker_container" "redis" {
  image = "redis:latest"
  name = "redis"
}
```

### Debug Output
https://gist.github.com/cowwoc/ef3a07507593ffe5cfadbfcf221eeadf

### Steps to Reproduce
1. `terraform plan`

**Comment by mavogel** [comment]
Thank for reporting. I need to give the windows usage a full revisit.

**Comment by cowwoc** [comment]
@mavidser To workaround this problem:

1. Go into Docker settings -> Enable "Expose daemon on tcp://localhost:2375 without TLS" (note this is a security risk!)
2. Set DOCKER_HOST to `tcp://localhost:2375` before running Terraform

I would love for this to work properly out-of-the-box without opening up that security hole. Thanks for looking into this.

**Comment by mishak87** [comment]
Actually workaround is to set host explicitly on windows

```

provider "docker" {
  version = "~> 2.6"
  host    = "npipe:////.//pipe//docker_engine"
}
```

I found the solution by digging trough the repository https://github.com/terraform-providers/terraform-provider-docker/pull/90/files#diff-7bc65d646d9528c16a2ea9addbbd8182R7

**Comment by mavogel** [comment]
@cowwoc can you verify the workaround mentioned above works for you?

**Comment by cowwoc** [comment]
Sorry, I'm not in a position to test the workaround. I'm not using terraform for any of my current projects.

**Comment by ffalorjr** [comment]
Hey @mavogel  the solution @mishak87 provided worked for me. Even when i disable Expose daemon on tcp://localhost:2375 without TLS

Thanks for the help!

**Comment by zarakM** [comment]
> Hey @mavogel the solution @mishak87 provided worked for me. Even when i disable Expose daemon on tcp://localhost:2375 without TLS
> 
> Terraform v0.12.21
> 
> * provider.docker v2.7.0
> 
> My provider:
> 
> ```
> provider "docker" {
>   host = "npipe:////.//pipe//docker_engine"
> }
> ```
> 
> Thanks for the help!

Can anyone tell me, how it makes a difference. It works for my scenario.

**Comment by alli40alli** [comment]
@mishak87 solution work perfecly

**Comment by alli40alli** [comment]
however it works only when I set  "Expose daemon on tcp://localhost:2375" to active in order to apply

**Comment by khteh** [comment]
> Actually workaround is to set host explicitly on windows
> 
> ```
> 
> provider "docker" {
>   version = "~> 2.6"
>   host    = "npipe:////.//pipe//docker_engine"
> }
> ```
> 
> I found the solution by digging trough the repository https://github.com/terraform-providers/terraform-provider-docker/pull/90/files#diff-7bc65d646d9528c16a2ea9addbbd8182R7

Where to add this config?
