### ISSUE TITLE
mount a single file in a volume

### ISSUE THREAD

**Issue by fredericrous** [terraform-providers/terraform-provider-docker#187]
### Terraform Version
Terraform v0.12.9
+ provider.docker v2.3.0

### Affected Resource(s)
- docker_container

### Terraform Configuration Files
```hcl
  volumes {
    host_path      = "${var.mount_point}/nginx/nginx.conf"
    container_path = "/etc/nginx/nginx.conf"
  }
```

### Debug Output
```
Error: Unable to start container: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"rootfs_linux.go:57: mounting \\\"/share/VMs/nginx/nginx.conf\\\" to rootfs \\\"/share/CACHEDEV6_DATA/VMs/container-station-data/lib/docker/overlay2/b29291ea4a812a1a469caed614e05591a3cdbf0728f5fc07bc920bd97a22a5cc/merged\\\" at \\\"/share/CACHEDEV6_DATA/VMs/container-station-data/lib/docker/overlay2/b29291ea4a812a1a469caed614e05591a3cdbf0728f5fc07bc920bd97a22a5cc/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

  on nginx.tf line 5, in resource "docker_container" "nginx":
   5: resource "docker_container" "nginx" {
```
Full log output: <https://gist.githubusercontent.com/fredericrous/bd57b05f87b15873a63d8903376fc113/raw/45ca2ca3c6d0f5cb74385429c5553c7581827034/terraform_docker.log>

### Expected Behavior
I should be able to mount a file on an existing file in order to override it by my own configuration

### Actual Behavior
I get an error

### Steps to Reproduce
`terraform apply`

**Comment by dubo-dubon-duponey** [comment]
This works as expected when the file already exist:

```
  volumes {
    host_path      = "/home/container/exist.conf"
    container_path = "/etc/nginx/nginx.conf"
  }
```

This does not if the file does not exist:

```
  volumes {
    host_path      = "/home/container/doesnotexist.conf"
    container_path = "/etc/nginx/nginx.conf"
  }
```

This last scenario gives exactly the same error you are getting.

Are you positive the file exist, and the container has permissions to read it?

Is there anything else "special" with your configuration? `/share/VMs` specifically?

**Comment by fredericrous** [comment]
The container I used was latest `nginx:1-alpine` from docker hub. I am positive the file already exists.
There is nothing special with `/share/VMs` all my containers mount subfolders within this path.
To give you more info, the version of docker I use is the one delivered with QNAP with their "Container Station" app: `Docker version 17.09.1-ce, build e398b97`

**Comment by dubo-dubon-duponey** [comment]
Interesting... I'm running docker 19.03, so, maybe this is related to 17.09.1.

Can you try the exact following steps?

Into an empty directory, create a terraform file with this:

```
variable pwd {
  default = "none"
}
data "docker_registry_image" "nginx" {
  name = "nginx:1-alpine"
}

resource "docker_image" "nginx" {
  name          = data.docker_registry_image.nginx.name
  pull_triggers = [data.docker_registry_image.nginx.sha256_digest]
}

resource "docker_container" "test" {
  name = "test"

  image = docker_image.nginx.name

  volumes {
    host_path = "${var.pwd}/nginx.conf"
    container_path = "/etc/nginx/nginx.conf"
  }
}
```

Then run the following script:

```
rm -Rf nginx.conf
touch nginx.conf
chmod a+r nginx.conf

docker run --name test-docker --volume $(pwd)/nginx.conf:/etc/nginx/nginx.conf nginx:1-alpine

terraform init .
terraform apply -auto-approve --var pwd=$(pwd) .
```

**Comment by fredericrous** [comment]
when I run `docker run --name test-docker --volume $(pwd)/nginx.conf:/etc/nginx/nginx.conf nginx:1-alpine`

I get:

```
[~/test] # docker run --name test-docker --volume $(pwd)/nginx.conf:/etc/nginx/nginx.conf nginx:1-alpine
2019/10/12 16:51:48 [emerg] 1#1: no "events" section in configuration
nginx: [emerg] no "events" section in configuration
```

When I run `terraform apply -auto-approve --var pwd=$(pwd) .`, I get:
<https://gist.githubusercontent.com/fredericrous/f4d4756f8119b248126cd51082065345/raw/385e206fd37aa21b18abc4742eb441ee5f517f0e/gistfile1.txt>

**Comment by dubo-dubon-duponey** [comment]
@fredericrous terraform is working as expected in that case, and the single file mount is successful (with /root/test/nginx.conf) ^.

I suggest you start (re-)introducing specifics of your environment into the example above to pinpoint what is causing an issue for you - starting with:

```
ls -lA /share/VMs/nginx
terraform apply -auto-approve --var pwd=/share/VMs/nginx
```

**Comment by fredericrous** [comment]
ok thx for the provided help. closing the issue for now
