### ISSUE TITLE
External Ports Option to not giving random port

### ISSUE THREAD

**Issue by guaychou** [terraform-providers/terraform-provider-docker#195]
Hi there,

### Terraform Version
![image](https://user-images.githubusercontent.com/29087469/66269493-43ed0280-e873-11e9-99a2-576964e36abf.png)

=> `0.12.9`

### Affected Resource(s)
Please list the resources as a list, for example:
- message_broker-container

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "docker" {
  host = "unix:///var/run/docker.sock"
}

resource "docker_image" "message_broker_image" {
  name = "lordchou/messagebroker-alpine:1.0.0"
}

resource "docker_image" "postfix_image" {
  name = "lordchou/postfix-alpine:1.0.0"
}

resource "docker_container" "message_broker_container" {
  image = "${docker_image.message_broker_image.name}"
  name  = "lordchou_messagebroker"
  ports  {
      internal = "21003"
      protocol = "tcp"
  }
  network_mode = "project_network"
}

resource "docker_container" "postfix_container" {
  image = "${docker_image.postfix_image.name}"
  count=3
  name  = "lordchou_postfix-${count.index+1}"
  env   = [
          "BROKER_HOST=lordchou_messagebroker",
  ]
  network_mode = "project_network"
  depends_on = [docker_container.message_broker_container]
}

resource "docker_network" "project_network" {
  name = "project_network"
}
```

### Expected Behavior
Port not exposed to random port number more than 32678

### Actual Behavior
What actually happened?

![image](https://user-images.githubusercontent.com/29087469/66269472-025c5780-e873-11e9-85c0-9b24aa82ea5c.png)
i get something like this , when i was'not define external port in container
i don't want to get random port, leave it blank , how can i get it ?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by mavogel** [comment]
hi @guaychou, I edited your issue a bit to conform it to the template. Could you please provide the missing sections. It will help me to understand your issue. Thanks

**Comment by guaychou** [comment]
hi @mavogel , oke edited , so what is difference terraform and docker-compose if i get random port number more than 32678 ?

**Comment by mavogel** [comment]
So @guaychou I don't be your expected behavior. Do you want
- no external port to be exposed?
- an external port to be exposed but < 32678?

AFAIK if you specify an internal port and no external you will get a random external port. If you do not want to have a port at all, leave it blank.

**Comment by guaychou** [comment]
@mavogel , Okay thank you for your explanation .
