### ISSUE TITLE
Don't hardcode UID, GID, & mode for Docker secrets and configs

### ISSUE THREAD

**Issue by tomalok** [terraform-providers/terraform-provider-docker#216]
### Terraform Version
Terraform v0.12.13

### Affected Resource(s)
- `docker_config`
- `docker_secret`

### Links to Source
- [`docker_secret`](https://github.com/terraform-providers/terraform-provider-docker/blob/master/docker/resource_docker_service_funcs.go#L900-L902)
- [`docker_secret`](https://github.com/terraform-providers/terraform-provider-docker/blob/master/docker/resource_docker_service_funcs.go#L921-L923)

### Expected Behavior
The UID, GID, and mode of Docker secrets and configs need to be configurable in some way, perhaps via `file_uid`, `file_gid`, and `file_mode` in `configs {}` and `secrets {}` blocks.  These should have default values that correspond with expected defaults if you used `docker config create` or `docker secret create` without specifying their values.

For example, some software checks to ensure that its PKI key is owned by the same UID as the the running process and that it is not readable by any other user. 

In theory, it shouldn't be too difficult to add these additional parameters.

**Comment by mavogel** [comment]
Hey @tomalok , thanks for pointing out! No that will not be difficult to change
