### ISSUE TITLE
Update dockerclient dependency

### ISSUE THREAD

**Issue by mavogel** [terraform-providers/terraform-provider-docker#22]
Hi @apparentlymart,

thanks for this awesome tool `terraform`. I'd like to update this provider to support the latest features of the [go-dockerclient](https://github.com/fsouza/go-dockerclient). Especially Swarm.

### Terraform Version
`v0.10.7`

### Terraform provider docker Version
`v0.1.0`

### Questions
- Do you need a release of the `go-dockerclient` to perform an update? 
I opened an issue and asked. The current version supports only up to the Docker 1.9 and API Version 1.21 (see [matrix](https://docs.docker.com/develop/sdk/#api-version-matrix)) 
**EDIT:** there is a new release now
- Why was `terraform-provider-docker-pull-19` not merged or uncommented for months? Because the build was failing? Or no comment was provided? Are there any Contribution Guidelines?

I'd really like to push this development forward 😃 

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- [go-dockerclient-685](https://github.com/fsouza/go-dockerclient/issues/685)
- [terraform-provider-docker-pull-19](https://github.com/terraform-providers/terraform-provider-docker/pull/19)

**Comment by mkuzmin** [comment]
Should we migrate to the official [Moby client](https://github.com/moby/moby/tree/master/client) instead?

**Comment by catsby** [comment]
Hey @mavogel – sorry for the trouble here. We don't currently have a volunteer maintainer for the Docker Provider so things have lingered and gone unattended to, sadly. 

We would happily accept contributions to upgrade and advance this provider though. 

It looks like your question about #19 was answered there. 

Hopefully I've answered some of your questions. Is maintainer-ship something you're interested in?

**Comment by mavogel** [comment]
Hey @catsby, no worries man. Thank you for the answers!
Great, I'm really interested in maintainer-ship 😃  we here at Stocard like to push the development of this provider forward. Let's do it 💪 

@mkuzmin - good point. I'll check this one out

**Comment by catsby** [comment]
@mavogel awesome, can you shoot me an email at clint @ hashicorp then, we have a semi-formal email to send to you about our expectations of maintainers, etiquette, etc. Thanks!

**Comment by mavogel** [comment]
Will be fixed with #31
