### ISSUE TITLE
Allow zero replicas for services

### ISSUE THREAD

**Issue by xanderflood** [terraform-providers/terraform-provider-docker#221]
The provider currently enforces that all configured `docker_service`s have [at least one replica](https://github.com/terraform-providers/terraform-provider-docker/blob/20b056aec2774c34e4e486f6af2fb66b0da86bc5/docker/resource_docker_service.go#L703). The underlying Swarm SDK supports zero replicas, and there are valid use cases for this:

1. When using the [swarm-cronjob tool](https://github.com/crazy-max/swarm-cronjob) to run a Docker container as a cron job, one configures a service with zero replicas and allows the swarm cron manager to instantiate the service as needed.
1. It's also useful for debugging by temporarily disabling a container without destroying the resource.

Since this is a one-character change, I went ahead and created a PR for it (https://github.com/terraform-providers/terraform-provider-docker/pull/220).

**Comment by xanderflood** [comment]
I added a note to #220 about the fact that #217 will screw it up, and it may screw up other intervening PRs as well. In most cases the unit tests should catch it, but not in this case because we're not unit testing all the validations (which seems reasonable to me). Whenever/ifever these two PRs are merged, there will need to be some code intervention between them.

**Comment by etienne-napoleone** [comment]
Yep can confirm it is needed in some cases for periodic jobs that are triggered from another source.
