### ISSUE TITLE
Getting registry information without `host` running docker daemon (such as on terraform Cloud / Enterprise)

### ISSUE THREAD

**Issue by dvcrn** [terraform-providers/terraform-provider-docker#227]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Terraform v0.12.16

### Affected Resource(s)
Please list the resources as a list, for example:
- docker

I recently migrated to Terraform Cloud and am running into some problems with the docker provider, more specifically that Terraform Cloud / Enterprise doesn't have a docker daemon running locally. 
I am using the docker provider to fetch image tags from a private registry, to update other resources such as kubernetes if necessary. 

My question is, is it possible to fetch docker information (such a tags and hashes) without using a daemon? Or are there plans to provide a daemon in Terraform Cloud?

**Comment by mavogel** [comment]
> My question is, is it possible to fetch docker information (such a tags and hashes) without using a daemon? Or are there plans to provide a daemon in Terraform Cloud?

Sorry @dvcrn I cannot answer this question, but maybe one of the core team like @radeksimko can.

**Comment by radeksimko** [comment]
I don't believe there are any public plans to run any such daemons in Terraform Cloud, but it may be best to direct any questions related to Terraform Cloud or Terraform Enterprise to our [official support channels](https://support.hashicorp.com).

The important question is what do you mean by "private registry". Is it just publicly available registry which requires users to be authenticated & authorized, or is it entirely "firewalled-off" from the internet?

In the former case you should be able to work with it from anywhere (including TFC/TFE), assuming you provide correct authentication to the provider.

The latter case boils down to a few much more generic questions (unrelated to Docker provider) with potentially more complex answers:

 - What does your network look like?
 - What are your best practices and expectations with regards to securing your network perimeter? 
 - Do you prefer running services internally for any (compliance?) reasons?

Depending on your answers to the above, one of the possible solutions may also be [TFE](https://www.terraform.io/docs/enterprise/index.html) - which is self-hosted solution that can run in your own network.

But again - I may not be familiar with all the details and current functionality TFC or TFE offers today or the roadmap of either. Filling a support ticket is therefore the best way forward as you will get the most accurate answer.

**Comment by dvcrn** [comment]
@radeksimko I missed your response - sorry! 

I meant it is a public registry, but requires users t be authenticated. 

> In the former case you should be able to work with it from anywhere (including TFC/TFE), assuming you provide correct authentication to the provider.

The problem for this is still that this provider requires the `host` key which should point to a docker daemon/client to be used to connect to the registry. Terraform Cloud/Enterprise doesn't have a docker client, so this provider can't be used. 

There are some hacks [over here](https://github.com/terraform-providers/terraform-provider-docker/issues/285), but it would be much nicer if this provider could just connect to those registries to at least query image tags and metadata through the docker API.
