### ISSUE TITLE
Connection to registry always required

### ISSUE THREAD

**Issue by madduci** [terraform-providers/terraform-provider-docker#24]
### Terraform Version
v0.10.8

### Affected Resource(s)
- docker_image

### Terraform Configuration Files
```
resource "docker_image" "jenkins" {
  name         = "jenkinsci/jenkins:lts-slim"
  keep_locally = true
}
```
### Output
```
Error: Error applying plan:

1 error(s) occurred:

* module.InternalInfrastructure.docker_image.jenkins: 1 error(s) occurred:

* docker_image.jenkins: Unable to read Docker image into resource: Unable to pull image jenkinsci/jenkins:lts-slim: Error pulling image jenkinsci/jenkins:lts-slim: API error (500): {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io: no such host"}
```

### Expected Behavior
Terraform should use the local image stored on a machine, without triggering a `docker pull` on the registry

### Actual Behavior
Terraform tries to pull a new image from a docker registry, even if an image is present in the local machine.

### Steps to Reproduce
`terraform apply`

**Comment by mavogel** [comment]
Closed in #143
