### ISSUE TITLE
add docker_registry_image resource with build support 

### ISSUE THREAD

**Issue by edgarpoce** [terraform-providers/terraform-provider-docker#248]
### Summary
Add a new resource called docker_registry_image that provides an image/tag in a docker registry such as AWS ECR

```hcl
resource "docker_registry_image" "helloworld" {
  name = "1234567890.dkr.ecr.us-east-1.amazonaws.com/helloworld:1.0"
  build {
    context = "pathToContextFolder"
  }
}
```

### Schema proposal
* `name` - (Required, string) The name of the Docker image.

* `keep_remotely` - (Optional, boolean) If true, then the Docker image won't be
  deleted on destroy operation. If this is false, it will delete the image from
  the docker registry on destroy operation.

* `build` - (Optional, Map) ... arguments from docker cli golang library

### Implementation proposal
- Optionally build the image if a build configuration is provided
- Create a context folder hash to identify whether the source files changed, store the context folder hash in the tf state 

### References
- #33

**Comment by mavogel** [comment]
close with #249
