### ISSUE TITLE
Support for --rm flag on containers

### ISSUE THREAD

**Issue by camjackson** [terraform-providers/terraform-provider-docker#43]
```sh
$ terraform -v
Terraform v0.11.3
+ provider.docker v0.1.0
```

I would like to launch a container which I know will be short-lived, and have it be cleaned up once it exits, similar to `docker run --rm`.

Looking at the docs for the golang Docker SDK, the [`ContainerCreate`](https://godoc.org/github.com/docker/docker/client#Client.ContainerCreate) function accepts a [`HostConfig`](https://godoc.org/github.com/docker/docker/api/types/container#HostConfig) object, which contains the relevant flag, `AutoRemove`.

It would be great if this flag was exposed like so:

```hcl
resource "docker_container" "my_containerised_script" {
  name  = "my_script"
  image = "my_script_image"
  rm = true
}
```

**Comment by bhuisgen** [comment]
Please check PR #106
