### ISSUE TITLE
Docker provider documentation says private registries not supported

### ISSUE THREAD

**Issue by jtatum** [terraform-providers/terraform-provider-docker#45]
https://www.terraform.io/docs/providers/docker/d/registry_image.html
https://www.terraform.io/docs/providers/docker/r/image.html

According to the changelog, the latest release supports pulling from private registries. Although the provider docs explain how to add credentials for multiple registries, the docker_registry_image data source and docker_image resource pages both indicate that private registries are not supported in the initial (current?) release.

**Comment by mavogel** [comment]
Hi, @jtatum you're right, I forgot to remove the `notes` that say that they are not supported. Will update the homepage on the next release. But to answer your question, yes private registries are supported

**Comment by mavogel** [comment]
Updated with https://github.com/terraform-providers/terraform-provider-docker/commit/c8bbdbc091e2c541c1a85af68e4d90383b010533
