### ISSUE TITLE
Using upload inside docker_container with binary files always forces a destroy

### ISSUE THREAD

**Issue by captn3m0** [terraform-providers/terraform-provider-docker#48]
### Terraform Version

``` tf11 --version
Terraform v0.11.4
+ provider.cloudflare v0.1.0
+ provider.digitalocean v0.1.3
+ provider.docker v0.1.1
+ provider.mysql v0.1.0
+ provider.template v1.0.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `docker_container`

### Terraform Configuration Files
```hcl
resource docker_container "docker-file-test" {
  name  = "docker-file-test"
  image = "${docker_image.docker-file-test.latest}"

  upload {
    content = "${file("${path.module}/files/1.txt")}"

    file = "/var/1.txt"
  }
}
```

### Debug Output

Both outputs are after running 1 apply with the relevant file

#### Output with plain text file

```bash
$ cat 1.txt && sha1sum 1.txt 
894fc3f56edf2d3a4c5fb5cb71df910f958a2ed8  -
4f459664a6b39e5f2cf595b37cfdfcb7d9740c17  1.txt
$ tf11 plan  --target module.docker-file-test
..
No changes. Infrastructure is up-to-date.
```

#### Output with a 2-byte binary file

```bash
cat 1.txt && echo && sha1sum 1.txt 
ñG
143fbaf9b82ba1b4f20faad9505e685e4d3639a4  1.txt
tf11 plan  --target module.docker-file-test
Terraform will perform the following actions:

-/+ module.docker-file-test.docker_container.docker-file-test (new resource required)
      id:                        "aba876dfa85d605266cabaadda63523db11bfa600d12c61c4731040b41593903" => <computed> (forces new resource)
      bridge:                    "" => <computed>
      gateway:                   "172.17.0.1" => <computed>
      image:                     "sha256:73acd1f0cfadf6f56d30351ac633056a4fb50d455fd95b229f564ff0a7adecda" => "sha256:73acd1f0cfadf6f56d30351ac633056a4fb50d455fd95b229f564ff0a7adecda"
      ip_address:                "172.17.0.26" => <computed>
      ip_prefix_length:          "16" => <computed>
      log_driver:                "json-file" => "json-file"
      must_run:                  "true" => "true"
      name:                      "docker-file-test" => "docker-file-test"
      restart:                   "no" => "no"
      upload.#:                  "1" => "1"
      upload.2067081083.content: "�G" => "" (forces new resource)
      upload.2067081083.file:    "/var/1.txt" => "" (forces new resource)
      upload.277341835.content:  "" => "\xf1G" (forces new resource)
      upload.277341835.file:     "" => "/var/1.txt" (forces new resource)


Plan: 1 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------

```

### Expected Behavior

The second plan should show `No Changes`, since the file on disk is matching the file on the container. This is important if you are uploading binaries to the container. In my case, this happens to be image files (logos/banners etc), which do not change, but give me dirty plans.

### Actual Behavior

A dirty plan is generated.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. Add the attached `1.txt` file to any docker_container using the same upload syntax as above.
2. Run a apply to make sure that the file uploads
3. Run another plan

I've seen the comment on the code:

```go
// This is intentional. The container is mutated once, and never updated later.
// New configuration forces a new deployment, even with the same binaries.
```

but it applies unequally to binary/text files which is quite confusing.

**Comment by bflad** [comment]
Hi @captn3m0! 👋  Sorry you're running into trouble here. Maybe an enhancement to this provider could be made or at least a documentation update.

Terraform currently requires UTF8 strings when saving content to its state. You can see the difference in these two lines in particular (the number changing is also due to the content representation changing):

```
      upload.2067081083.content: "�G" => "" (forces new resource)
      upload.277341835.content:  "" => "\xf1G" (forces new resource)
```

For various other providers, we work around this by accepting an additional attribute, `content_base64`, that will take in a Base64 encoded string of a binary (what gets saved in the Terraform state) and decode it before working with the backend. Here's an example of the implementation from the AWS provider: https://github.com/terraform-providers/terraform-provider-aws/pull/3788

Hope this helps!

**Comment by captn3m0** [comment]
Thanks, this does help me understand the problem :+1: 

Any suggestions for workarounds?

**Comment by mavogel** [comment]
thx @bflad for the update. I'll add this feature and fix the bug

**Comment by captn3m0** [comment]
I tried using ignore_changes, but it doesn't seem to work either:

```hcl

**Comment by captn3m0** [comment]
Can this please be done in the next release. The content attributes are useless for binary files as of now.

**Comment by mavogel** [comment]
on it @captn3m0! Waiting for feedback for a testing issue. But in the logs everything is fine

**Comment by mavogel** [comment]
I tested it locally (it's not possible in the acc tests: see #194  for details) with the following config

```sh
cat 1.txt               
894fc3f56edf2d3a4c5fb5cb71df910f958a2ed8
shasum 1.txt 
14d1bc5f61a6f57338ca68bb5da2c54cf2315746  1.txt
```

```hcl
provider "docker" {
    version ="~> 2.4.0"
}


resource "docker_image" "foo" {
	name         = "nginx:latest"
	keep_locally = true
}

resource "docker_container" "foo" {
	name  = "tf-test"
	image = "${docker_image.foo.latest}"

	upload {
		content_base64 = "${base64encode("6f1b2a425192b10a15090c0fdea8f4cd137daab042070133682d4317adc69e6b")}"
		file           = "/terraform/test1.txt"
		executable     = true
	}

	upload {
		content_base64 = "${base64encode(file("1.txt"))}"
		file           = "/terraform/test2.txt"
		executable     = true
	}
}
```

- the decoded string in the file in the container
```sh
docker exec -it tf-test cat /terraform/test2.txt
894fc3f56edf2d3a4c5fb5cb71df910f958a2ed8
```
- and the encoded string in the state
```json
{
"upload": [
              {
                "content": "",
                "content_base64": "NmYxYjJhNDI1MTkyYjEwYTE1MDkwYzBmZGVhOGY0Y2QxMzdkYWFiMDQyMDcwMTMzNjgyZDQzMTdhZGM2OWU2Yg==",
                "executable": true,
                "file": "/terraform/test1.txt"
              },
              {
                "content": "",
                "content_base64": "ODk0ZmMzZjU2ZWRmMmQzYTRjNWZiNWNiNzFkZjkxMGY5NThhMmVkOA==",
                "executable": true,
                "file": "/terraform/test2.txt"
              }
            ],
}
```
