### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by captn3m0** [terraform-providers/terraform-provider-docker#69]
The last release (v0.1.1) is quite old (November 2017).

Lots of commits to master since: https://github.com/terraform-providers/terraform-provider-docker/compare/v0.1.1...master

A new release will be very helpful.

**Comment by mavogel** [comment]
@captn3m0 it is one the way :) 
- The fact is with the current client to connect to the Docker API is it not possible to build. See https://github.com/fsouza/go-dockerclient/issues/733 for details
- So I decided to migrate to the offical client: https://github.com/fsouza/go-dockerclient/issues/733 Feel free to help :) The `migrate/docker-client` branch is pushed
- But the next issue which is faced is the following, even with the offical client the provider cannot be built for `solaris`
```sh
--> solaris/amd64 error: exit status 2
Stderr: # github.com/terraform-providers/terraform-provider-docker/vendor/github.com/docker/docker/client
vendor/github.com/docker/docker/client/client.go:238:35: undefined: DefaultDockerHost
vendor/github.com/docker/docker/client/client.go:243:12: undefined: DefaultDockerHost
vendor/github.com/docker/docker/client/client.go:247:12: undefined: defaultProto
vendor/github.com/docker/docker/client/client.go:248:12: undefined: defaultAddr
```
Apparently `Docker` disabled the support: https://github.com/moby/moby/commit/1589cc0a85396e2768bfe9e558c7c2100dc3bc87 and https://github.com/moby/moby/commit/5a9b5f10cf967f31f0856871ad08f9a0286b4a46 for this OS.

So we agreed to disable this OS for the build. The implementation of remaining resources fixing the tests is left. As already mentioned. Feel free to help to migrate the code :-) Just let me know which resources you want to tackle ;-)

**Comment by mavogel** [comment]
Version `1.0.0` got released https://releases.hashicorp.com/terraform-provider-docker/1.0.0/ 
Try it out :)

**Comment by captn3m0** [comment]
Thanks a lot. :+1:
