### ISSUE TITLE
data source: network

### ISSUE THREAD

**Issue by captn3m0** [terraform-providers/terraform-provider-docker#84]
I keep having to pass around the docker network IDs as:

```hcl
output "traefik-network-id" {
  value = "${docker_network.traefik.id}"
}
```

And then use them in other places. Would prefer if there was a data source that lets me look up networks using name or other conditions. Something like the following:

```hcl
data "docker_network" "one"{
  id = ""
  name = "network-1"
}

data "docker_networks" "list" {
  driver = ""
  label {
    key = "value"
  }
  // Matches partial name
  name = ""
  type = "custom|builtin"
}
```

The singular `docker_network` always returns one exact return by the `name` or `id`. The `docker_networks` returns a list of networks. 

The exported attributes will be same as `docker_network` resource.

Will try to file a PR for this if this sounds like a good idea?

**Comment by captn3m0** [comment]
The list of parameters is based on the filters at https://docs.docker.com/engine/api/v1.24/#35-networks

```
- driver=<driver-name> Matches a network’s driver.
- id=<network-id> Matches all or part of a network id.
- label=<key> or label=<key>=<value> of a network label.
- name=<network-name> Matches all or part of a network name.
- type=["custom"|"builtin"] Filters networks by type. The custom keyword returns all user-defined networks.
```

**Comment by mavogel** [comment]
Sounds like a good idea to me and the other maintainers. I gathered some feedback about this @captn3m0 . PRs are welcome :)

**Comment by captn3m0** [comment]
I've filed https://github.com/terraform-providers/terraform-provider-docker/pull/87
